#!/usr/bin/env ruby
require 'hkendall_palindrome'
require 'open-uri'

palindromes = URI.open('https://cdn.learnenough.com/phrases.txt').readlines.select(&:palindrome?)
palindromes.each { |palindrome| puts "palindrome detected: #{palindrome}" }
File.write('palindrome_url.txt', palindromes.join)