source 'https://rubygems.org'

ruby '3.2.0'

gem 'sinatra', '2.2.2'
gem 'puma', '5.6.5'
gem 'rerun', '0.14.0'
gem 'hkendall_palindrome', '0.2.1'

group :test do
  gem 'minitest',           '5.15.0'
  gem 'minitest-reporters', '1.5.0'
  gem 'rack-test',          '1.1.0'
  gem 'rake',               '13.0.6'
  gem 'nokogiri',           '1.15.3'
end

