#!/usr/bin/env ruby
require 'open-uri'
require 'nokogiri'

# Returns the paragraphs from a Wikipedia link, stripped of reference numbers.
# Especially useful for text-to-speech (both native and foreign).

url = ARGV.shift
if url == nil
  puts "Please specify a URL."
  abort
else
  doc = Nokogiri::HTML(open(url).read)
  doc.css('.reference').each(&:remove)
  puts doc.css('p').map(&:content).join("\n")
end